#include "VideoBwDecoder.h"
#include "config.h"

VideoBwDecoder::VideoBwDecoder()
{}

void VideoBwDecoder::Decode4x4Bin( uint8_t a, uint8_t b )
{
    if ( (a & 1) != 0 )
    { TFT_DATAPIN_SET(0xFF); TFT_SWAP_DATA_WR TFT_SWAP_DATA_WR } else
    { TFT_DATAPIN_SET(0x00); TFT_SWAP_DATA_WR TFT_SWAP_DATA_WR }

    if ( (a & 2) != 0 )
    { TFT_DATAPIN_SET(0xFF); TFT_SWAP_DATA_WR TFT_SWAP_DATA_WR } else
    { TFT_DATAPIN_SET(0x00); TFT_SWAP_DATA_WR TFT_SWAP_DATA_WR }

    if ( (a & 4) != 0 )
    { TFT_DATAPIN_SET(0xFF); TFT_SWAP_DATA_WR TFT_SWAP_DATA_WR } else
    { TFT_DATAPIN_SET(0x00); TFT_SWAP_DATA_WR TFT_SWAP_DATA_WR }

	if ( (a & 8) != 0 )
    { TFT_DATAPIN_SET(0xFF); TFT_SWAP_DATA_WR TFT_SWAP_DATA_WR } else
    { TFT_DATAPIN_SET(0x00); TFT_SWAP_DATA_WR TFT_SWAP_DATA_WR }

	if ( (a & 16) != 0 )
    { TFT_DATAPIN_SET(0xFF); TFT_SWAP_DATA_WR TFT_SWAP_DATA_WR } else
    { TFT_DATAPIN_SET(0x00); TFT_SWAP_DATA_WR TFT_SWAP_DATA_WR }

	if ( (a & 32) != 0 )
    { TFT_DATAPIN_SET(0xFF); TFT_SWAP_DATA_WR TFT_SWAP_DATA_WR } else
    { TFT_DATAPIN_SET(0x00); TFT_SWAP_DATA_WR TFT_SWAP_DATA_WR }

	if ( (a & 64) != 0 )
    { TFT_DATAPIN_SET(0xFF); TFT_SWAP_DATA_WR TFT_SWAP_DATA_WR } else
    { TFT_DATAPIN_SET(0x00); TFT_SWAP_DATA_WR TFT_SWAP_DATA_WR }

	if ( (a & 128) != 0 )
    { TFT_DATAPIN_SET(0xFF); TFT_SWAP_DATA_WR TFT_SWAP_DATA_WR } else
    { TFT_DATAPIN_SET(0x00); TFT_SWAP_DATA_WR TFT_SWAP_DATA_WR }

	if ( (b & 1) != 0 )
    { TFT_DATAPIN_SET(0xFF); TFT_SWAP_DATA_WR TFT_SWAP_DATA_WR } else
    { TFT_DATAPIN_SET(0x00); TFT_SWAP_DATA_WR TFT_SWAP_DATA_WR }

    if ( (b & 2) != 0 )
    { TFT_DATAPIN_SET(0xFF); TFT_SWAP_DATA_WR TFT_SWAP_DATA_WR } else
    { TFT_DATAPIN_SET(0x00); TFT_SWAP_DATA_WR TFT_SWAP_DATA_WR }

    if ( (b & 4) != 0 )
    { TFT_DATAPIN_SET(0xFF); TFT_SWAP_DATA_WR TFT_SWAP_DATA_WR } else
    { TFT_DATAPIN_SET(0x00); TFT_SWAP_DATA_WR TFT_SWAP_DATA_WR }

	if ( (b & 8) != 0 )
    { TFT_DATAPIN_SET(0xFF); TFT_SWAP_DATA_WR TFT_SWAP_DATA_WR } else
    { TFT_DATAPIN_SET(0x00); TFT_SWAP_DATA_WR TFT_SWAP_DATA_WR }

	if ( (b & 16) != 0 )
    { TFT_DATAPIN_SET(0xFF); TFT_SWAP_DATA_WR TFT_SWAP_DATA_WR } else
    { TFT_DATAPIN_SET(0x00); TFT_SWAP_DATA_WR TFT_SWAP_DATA_WR }

	if ( (b & 32) != 0 )
    { TFT_DATAPIN_SET(0xFF); TFT_SWAP_DATA_WR TFT_SWAP_DATA_WR } else
    { TFT_DATAPIN_SET(0x00); TFT_SWAP_DATA_WR TFT_SWAP_DATA_WR }

	if ( (b & 64) != 0 )
    { TFT_DATAPIN_SET(0xFF); TFT_SWAP_DATA_WR TFT_SWAP_DATA_WR } else
    { TFT_DATAPIN_SET(0x00); TFT_SWAP_DATA_WR TFT_SWAP_DATA_WR }

	if ( (b & 128) != 0 )
    { TFT_DATAPIN_SET(0xFF); TFT_SWAP_DATA_WR TFT_SWAP_DATA_WR } else
    { TFT_DATAPIN_SET(0x00); TFT_SWAP_DATA_WR TFT_SWAP_DATA_WR }
}
